apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-library
  template:
    metadata:
      labels:
        app: digital-library
    spec:
      containers:
      - name: django
        image: yourdockerhub/digital-library:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: django-secret