apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: dXNlLXlvdXItYWN0dWFsLXNlY3JldA==
  DB_NAME: bGlicmFyeQ==
  DB_USER: bGlicmFyeV91c2Vy
  DB_PASSWORD: cGFzc3dvcmQ=